modLoader="javafml"
loaderVersion="[41,)"
license="MIT"
issueTrackerURL="https://github.com/Kay9Unit/Dragon-Mounts-Legacy/issues"
[[mods]]
modId="dragonmounts"
version="${file.jarVersion}"
displayName="Dragon Mounts: Legacy"
#logoFile="examplemod.png"
credits="ata4/barracuda for the original project and idea."
authors="Kay9"
description='''This is a mod that allows you to hatch previously useless dragon eggs.
Once fostered and tamed, they'll be your faithful companion in all situations and, of course, can be used for a ride!'''
[[dependencies.dragonmounts]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.100,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dragonmounts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
